export interface DataType {
    id: number,
    name: string,
    address: string,
    name_order: string,
    created_date: string,
    end_date: string,
    actual_date: string,
    price: number,
    prepayment: number,
    status: string,
    comment: string,
    difficulty: string,
    responsible: string,
    offer: string,
}